apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: w8t-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: w8t-mysql
  template:
    metadata:
      labels:
        app: w8t-mysql
    spec:
      containers:
        - name: w8t-mysql
          image: mysql:8.0
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: w8t.123
            - name: MYSQL_DATABASE
              value: watchalert
            - name: TZ
              value: Asia/Shanghai
          ports:
            - containerPort: 3306
          {{- if .Values.mysql.persistence.enabled }}
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          {{- end }}

  {{- if .Values.mysql.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["{{ .Values.mysql.persistence.accessModes }}"]
        storageClassName: "{{ .Values.mysql.persistence.storageClass }}"
        resources:
          requests:
            storage: "{{ .Values.mysql.persistence.size }}"
  {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: w8t-mysql
spec:
  selector:
    app: w8t-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306